#!/usr/bin/env python3
"""
Build an interactive 2D force-graph visualization of Readwise highlights.

Usage:
    python3 build_graph.py --highlights highlights.json --connections connections.json --output highlight-graph.html

highlights.json: array of {id, text, note, book_id, source_title, source_author, url}
connections.json: array of {a_id, b_id, label, why}  (cross-source semantic connections)

Both files are generated by the LLM as part of the highlight-graph skill.
"""

import json
import argparse
import sys
from collections import defaultdict


def build_graph(highlights, connections, output_path):
    # Filter out junk highlights
    highlights = [
        h for h in highlights
        if not h['text'].startswith('Finished Document:')
        and not h['text'].startswith('Archived this document:')
        and len(h['text'].strip()) >= 20
    ]

    # Dedupe by id
    seen_ids = set()
    deduped_h = []
    for h in highlights:
        hid = str(h['id'])
        if hid not in seen_ids:
            seen_ids.add(hid)
            h['id'] = hid
            deduped_h.append(h)
    highlights = deduped_h

    # Source counts and colors
    source_counts = {}
    for h in highlights:
        source_counts[h['book_id']] = source_counts.get(h['book_id'], 0) + 1

    palette = [
        '#c4a7e7', '#9ccfd8', '#f6c177', '#eb6f92', '#e0def4',
        '#31748f', '#ebbcba', '#908caa', '#56949f', '#d7827e',
        '#286983', '#ea9d34', '#b4637a', '#575279', '#cecacd',
        '#907aa9', '#56949f', '#d7827e', '#286983', '#ea9d34',
    ]
    source_ids = sorted(source_counts.keys(), key=lambda x: -source_counts[x])
    source_colors = {sid: palette[i % len(palette)] for i, sid in enumerate(source_ids)}

    # Build nodes
    nodes = []
    for h in highlights:
        preview = h['text'][:120].replace('\n', ' ').replace('"', "'") + ('…' if len(h['text']) > 120 else '')
        nodes.append({
            'id': f'h_{h["id"]}',
            'preview': preview,
            'fullText': h['text'],
            'note': h.get('note', ''),
            'sourceTitle': h.get('source_title', 'Unknown'),
            'sourceAuthor': h.get('source_author', 'Unknown'),
            'url': h.get('url', ''),
            'color': source_colors.get(h['book_id'], '#908caa'),
            'bookId': h['book_id'],
        })

    # Same-source full pairwise connectivity
    links = []
    by_source = defaultdict(list)
    for h in highlights:
        by_source[h['book_id']].append(h['id'])
    for bid, hids in by_source.items():
        for i in range(len(hids)):
            for j in range(i + 1, len(hids)):
                links.append({
                    'source': f'h_{hids[i]}',
                    'target': f'h_{hids[j]}',
                    'type': 'same',
                })

    # Cross-source connections
    valid_ids = {h['id'] for h in highlights}
    connections = [c for c in connections if str(c['a_id']) in valid_ids and str(c['b_id']) in valid_ids]

    # Dedupe
    seen_pairs = set()
    deduped_c = []
    for c in connections:
        pair = tuple(sorted([str(c['a_id']), str(c['b_id'])]))
        if pair not in seen_pairs:
            seen_pairs.add(pair)
            deduped_c.append(c)
    connections = deduped_c

    node_map = {n['id']: n for n in nodes}
    conn_js = []
    for conn in connections:
        a_id = f'h_{conn["a_id"]}'
        b_id = f'h_{conn["b_id"]}'
        a_node = node_map.get(a_id, {})
        b_node = node_map.get(b_id, {})
        if not a_node or not b_node:
            continue
        conn_js.append({
            'a_id': a_id,
            'b_id': b_id,
            'a_source': a_node.get('sourceTitle', ''),
            'b_source': b_node.get('sourceTitle', ''),
            'a_fullText': a_node.get('fullText', '')[:250],
            'b_fullText': b_node.get('fullText', '')[:250],
            'label': conn.get('label', ''),
            'why': conn.get('why', ''),
        })
        links.append({
            'source': a_id,
            'target': b_id,
            'type': 'cross',
            'label': conn.get('label', ''),
        })

    # Legend: sources with 2+ highlights
    source_legend = []
    for sid in source_ids:
        if source_counts[sid] < 2:
            continue
        # Find title/author from first highlight with this book_id
        src_h = next((h for h in highlights if h['book_id'] == sid), None)
        source_legend.append({
            'title': src_h['source_title'] if src_h else 'Unknown',
            'color': source_colors[sid],
            'count': source_counts[sid],
            'bookId': sid,
        })

    graph_data = {'nodes': nodes, 'links': links}
    valid_conns = len(conn_js)

    print(f'Highlights: {len(nodes)}, Sources: {len(source_legend)}, Cross-connections: {valid_conns}')

    # Build legend HTML
    legend_html = ''
    for i, s in enumerate(source_legend):
        legend_html += (
            f'<div class="it" onclick="filterSrc(this,{s["bookId"]})">'
            f'<span class="dt" style="background:{s["color"]}"></span>'
            f'<span>{s["title"]}</span>'
            f'<span class="ct">{s["count"]}</span>'
            f'</div>'
        )

    html = TEMPLATE.replace('__GRAPH_DATA__', json.dumps(graph_data))
    html = html.replace('__CONN_INDEX__', json.dumps(conn_js))
    html = html.replace('__LEGEND_HTML__', legend_html)
    html = html.replace('__NUM_HIGHLIGHTS__', str(len(nodes)))
    html = html.replace('__NUM_SOURCES__', str(len(source_legend)))
    html = html.replace('__NUM_CONNECTIONS__', str(valid_conns))

    with open(output_path, 'w') as f:
        f.write(html)
    print(f'Written to {output_path}')
    return {
        'highlights': len(nodes),
        'sources': len(source_legend),
        'connections': valid_conns,
        'path': output_path,
    }


TEMPLATE = r'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Highlight Graph</title>
<link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@300;400;500&family=Crimson+Pro:ital,wght@0,400;0,600;1,400&display=swap" rel="stylesheet">
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { background:#1e1e1e; color:#d0d0d0; font-family:'DM Mono',monospace; overflow:hidden; }
  #graph { width:100vw; height:100vh; }
  #stats {
    position:fixed; top:14px; left:18px; font-size:11px; color:#555;
    letter-spacing:0.5px; text-transform:uppercase; display:flex; gap:14px;
  }
  #stats .v { color:#c4a7e7; font-weight:500; }
  #controls { position:fixed; bottom:14px; left:18px; font-size:11px; color:#383838; pointer-events:none; }
  #edge-tooltip {
    position:fixed; padding:4px 8px; background:rgba(30,30,30,0.95);
    border:1px solid rgba(196,167,231,0.4); border-radius:3px;
    font-size:10px; color:#c4a7e7; pointer-events:none;
    display:none; z-index:30; white-space:nowrap; letter-spacing:0.3px;
  }
  #legend {
    position:fixed; top:14px; right:18px; font-size:10px; color:#444;
    max-height:45vh; overflow-y:auto; scrollbar-width:none;
  }
  #legend::-webkit-scrollbar { display:none; }
  #legend .it {
    display:flex; align-items:center; gap:6px; margin-bottom:2px;
    cursor:pointer; padding:2px 4px; border-radius:3px; transition:background 0.2s;
  }
  #legend .it:hover { background:#252525; }
  #legend .it.active { background:#252525; color:#aaa; }
  #legend .dt { width:6px; height:6px; border-radius:50%; flex-shrink:0; }
  #legend .ct { color:#333; margin-left:auto; }
  #panel {
    position:fixed; top:0; right:-480px; width:460px; height:100vh;
    background:rgba(24,24,24,0.97); border-left:1px solid #2a2a2a;
    padding:32px 28px; overflow-y:auto; transition:right 0.3s cubic-bezier(0.4,0,0.2,1);
    z-index:10; backdrop-filter:blur(20px); scrollbar-width:thin; scrollbar-color:#2a2a2a transparent;
  }
  #panel.open { right:0; }
  #panel .close {
    position:absolute; top:14px; right:18px; cursor:pointer;
    font-size:14px; color:#444; background:none; border:none;
    font-family:'DM Mono',monospace; transition:color 0.2s;
  }
  #panel .close:hover { color:#e0e0e0; }
  #panel .src {
    color:#555; font-size:10px; margin-bottom:16px;
    text-transform:uppercase; letter-spacing:1px;
    display:flex; align-items:center; gap:8px;
  }
  #panel .src-dot { width:6px; height:6px; border-radius:50%; }
  #panel .ht {
    font-family:'Crimson Pro',serif; font-size:15px; line-height:1.4;
    color:#ccc; margin-bottom:14px; white-space:pre-wrap;
  }
  #panel .nt {
    color:#c4a7e7; font-family:'DM Mono',monospace; font-size:11px;
    border-left:2px solid rgba(196,167,231,0.3); padding-left:12px;
    margin-bottom:14px; line-height:1.35;
  }
  #panel .ur { margin-bottom:24px; }
  #panel .ur a { color:#9ccfd8; text-decoration:none; font-size:11px; opacity:0.7; transition:opacity 0.2s; }
  #panel .ur a:hover { opacity:1; }
  #cs, #sb { border-top:1px solid #2a2a2a; padding-top:20px; }
  #cs h3, #sb h3 {
    color:rgba(196,167,231,0.6); font-size:10px; font-weight:500;
    margin-bottom:14px; text-transform:uppercase; letter-spacing:1.5px;
  }
  #sb h3 { color:rgba(156,207,216,0.6); }
  .sb-item {
    padding:6px 0; cursor:pointer; color:#666; font-size:12px;
    font-family:'Crimson Pro',serif; line-height:1.35; transition:color 0.2s;
    border-bottom:1px solid #1a1a1a;
  }
  .sb-item:hover { color:#ccc; }
  .sb-item:last-child { border-bottom:none; }
  .cc {
    background:#1a1a1a; border:1px solid #252525; border-radius:6px;
    padding:10px 14px; margin-bottom:8px; cursor:pointer;
    transition:border-color 0.25s, background 0.25s;
  }
  .cc:hover { border-color:rgba(196,167,231,0.3); background:#1e1e1e; }
  .cc .cl { color:#c4a7e7; font-size:11px; font-weight:500; margin-bottom:6px; letter-spacing:0.3px; }
  .cc .cw { color:#555; font-size:11px; margin-bottom:8px; line-height:1.3; }
  .cc .co { color:#3a3a3a; font-size:9px; text-transform:uppercase; letter-spacing:0.5px; margin-bottom:4px; }
  .cc .ct { font-family:'Crimson Pro',serif; color:#888; font-size:12px; line-height:1.35; font-style:italic; }
</style>
</head>
<body>
<div id="graph"></div>
<div id="stats">
  <span><span class="v">__NUM_HIGHLIGHTS__</span> highlights</span>
  <span><span class="v">__NUM_SOURCES__</span> sources</span>
  <span><span class="v">__NUM_CONNECTIONS__</span> connections</span>
</div>
<div id="controls">scroll zoom · drag pan · hover to focus · click to read</div>
<div id="edge-tooltip"></div>
<div id="legend">__LEGEND_HTML__</div>
<div id="panel">
  <button class="close" onclick="closePanel()">esc</button>
  <div class="src"><span class="src-dot" id="pd"></span><span id="ps"></span></div>
  <div class="ht" id="pt"></div>
  <div class="nt" id="pn" style="display:none"></div>
  <div class="ur" id="pu"></div>
  <div id="cs" style="display:none">
    <h3>Connected Ideas</h3>
    <div id="cl"></div>
  </div>
  <div id="sb" style="display:none">
    <h3>From This Source</h3>
    <div id="sl"></div>
  </div>
</div>

<script src="https://unpkg.com/force-graph"></script>
<script>
const data = __GRAPH_DATA__;
const connIndex = __CONN_INDEX__;

const nodeMap = {};
data.nodes.forEach(n => nodeMap[n.id] = n);

const connByNode = {};
connIndex.forEach(c => {
  if (!connByNode[c.a_id]) connByNode[c.a_id] = [];
  if (!connByNode[c.b_id]) connByNode[c.b_id] = [];
  connByNode[c.a_id].push({label:c.label,why:c.why,other_id:c.b_id,other_source:c.b_source,other_fullText:c.b_fullText});
  connByNode[c.b_id].push({label:c.label,why:c.why,other_id:c.a_id,other_source:c.a_source,other_fullText:c.a_fullText});
});

const neighbors = {};
data.links.forEach(l => {
  const s = typeof l.source === 'object' ? l.source.id : l.source;
  const t = typeof l.target === 'object' ? l.target.id : l.target;
  if (!neighbors[s]) neighbors[s] = new Set();
  if (!neighbors[t]) neighbors[t] = new Set();
  neighbors[s].add(t);
  neighbors[t].add(s);
});

let hoverNode = null;
let selectedNode = null;
let filterBookId = null;

function activeNode() { return hoverNode || selectedNode; }

function isConn(id) {
  const a = activeNode();
  if (!a) return true;
  if (id === a.id) return true;
  return neighbors[a.id] && neighbors[a.id].has(id);
}

function esc(s) { const d = document.createElement('div'); d.textContent = s; return d.innerHTML; }
function closePanel() { selectedNode = null; document.getElementById('panel').classList.remove('open'); }

function showNode(nodeId) {
  const n = nodeMap[nodeId];
  if (!n) return;
  document.getElementById('pd').style.background = n.color;
  document.getElementById('ps').textContent = n.sourceTitle + ' — ' + n.sourceAuthor;
  document.getElementById('pt').textContent = n.fullText;
  const ne = document.getElementById('pn');
  if (n.note) { ne.textContent = n.note; ne.style.display = 'block'; } else { ne.style.display = 'none'; }
  const ue = document.getElementById('pu');
  ue.innerHTML = n.url ? '<a href="'+esc(n.url)+'" target="_blank">open source →</a>' : '';
  const cs = document.getElementById('cs');
  const cl = document.getElementById('cl');
  const conns = connByNode[nodeId];
  if (conns && conns.length) {
    cl.innerHTML = conns.map(c => {
      const t = c.other_fullText.length > 180 ? c.other_fullText.substring(0,180)+'…' : c.other_fullText;
      return '<div class="cc" onclick="selectedNode=nodeMap[\''+c.other_id+'\'];showNode(\''+c.other_id+'\');Graph.centerAt(nodeMap[\''+c.other_id+'\'].x,nodeMap[\''+c.other_id+'\'].y,800);Graph.zoom(4,800);">'+
        '<div class="cl">'+esc(c.label)+'</div>'+
        '<div class="cw">'+esc(c.why)+'</div>'+
        '<div class="co">'+esc(c.other_source)+'</div>'+
        '<div class="ct">'+esc(t)+'</div></div>';
    }).join('');
    cs.style.display = 'block';
  } else { cs.style.display = 'none'; }
  const sb = document.getElementById('sb');
  const sl = document.getElementById('sl');
  const siblings = data.nodes.filter(o => o.bookId === n.bookId && o.id !== nodeId);
  if (siblings.length) {
    sl.innerHTML = siblings.map(s => {
      const t = s.fullText.length > 120 ? s.fullText.substring(0,120)+'…' : s.fullText;
      return '<div class="sb-item" onclick="selectedNode=nodeMap[\''+s.id+'\'];showNode(\''+s.id+'\');Graph.centerAt(nodeMap[\''+s.id+'\'].x,nodeMap[\''+s.id+'\'].y,800);Graph.zoom(4,800);">'+esc(t)+'</div>';
    }).join('');
    sb.style.display = 'block';
  } else { sb.style.display = 'none'; }
  document.getElementById('panel').classList.add('open');
  document.getElementById('panel').scrollTop = 0;
}

function filterSrc(el, bid) {
  const items = document.querySelectorAll('#legend .it');
  const was = el.classList.contains('active');
  items.forEach(i => i.classList.remove('active'));
  if (!was) { el.classList.add('active'); filterBookId = bid; }
  else { filterBookId = null; }
}

const edgeTooltip = document.getElementById('edge-tooltip');

let labelBoxes = [];
function boxOverlaps(bx, by, bw, bh) {
  const pad = 2;
  for (const b of labelBoxes) {
    if (bx < b.x + b.w + pad && bx + bw + pad > b.x &&
        by < b.y + b.h + pad && by + bh + pad > b.y) return true;
  }
  return false;
}

const Graph = ForceGraph()(document.getElementById('graph'))
  .graphData(data)
  .backgroundColor('#1e1e1e')
  .onRenderFramePre(() => { labelBoxes = []; })
  .nodeCanvasObject((node, ctx, globalScale) => {
    const a = activeNode();
    const r = node === a ? 3 : (connByNode[node.id] ? 2 : 1.5);
    let alpha = 0.85;
    if (a && !isConn(node.id)) alpha = 0.06;
    if (filterBookId !== null) alpha = node.bookId === filterBookId ? 0.9 : 0.05;

    if (node === a) {
      const grad = ctx.createRadialGradient(node.x, node.y, r, node.x, node.y, r * 8);
      grad.addColorStop(0, node.color + '40');
      grad.addColorStop(1, 'transparent');
      ctx.fillStyle = grad;
      ctx.beginPath();
      ctx.arc(node.x, node.y, r * 8, 0, 2 * Math.PI);
      ctx.fill();
    }

    if (a && node !== a && isConn(node.id) && connByNode[node.id]) {
      const grad = ctx.createRadialGradient(node.x, node.y, r, node.x, node.y, r * 6);
      grad.addColorStop(0, node.color + '20');
      grad.addColorStop(1, 'transparent');
      ctx.fillStyle = grad;
      ctx.beginPath();
      ctx.arc(node.x, node.y, r * 6, 0, 2 * Math.PI);
      ctx.fill();
    }

    ctx.globalAlpha = alpha;
    ctx.fillStyle = node.color;
    ctx.beginPath();
    ctx.arc(node.x, node.y, r, 0, 2 * Math.PI);
    ctx.fill();
    ctx.globalAlpha = 1;

    const isActive = node === a;

    if (alpha > 0.1) {
      const fontSize = 2;

      {
        const label = node.preview || node.sourceTitle;
        const maxW = 30;
        const lineH = fontSize * 1.3;

        const srcLabel = node.sourceTitle;
        ctx.font = `${fontSize * 0.85}px 'DM Mono', monospace`;
        const srcW = ctx.measureText(srcLabel).width;

        ctx.font = `${fontSize}px 'DM Mono', monospace`;
        const words = label.split(' ');
        let lines = [];
        let line = '';
        for (let i = 0; i < words.length; i++) {
          const test = line ? line + ' ' + words[i] : words[i];
          if (ctx.measureText(test).width > maxW && line) {
            lines.push(line);
            line = words[i];
          } else { line = test; }
        }
        lines.push(line);

        const x = node.x + r + 3;
        const srcH = fontSize * 0.85 * 1.4;
        const y0 = node.y - fontSize * 0.5;
        const totalH = srcH + lines.length * lineH;
        const totalW = Math.min(maxW, Math.max(srcW, ...lines.map(l => ctx.measureText(l).width)));

        if (!isActive && boxOverlaps(x, y0, totalW, totalH)) {
          // skip — would overlap
        } else {
          labelBoxes.push({x, y: y0, w: totalW, h: totalH});
          ctx.textAlign = 'left';
          ctx.textBaseline = 'top';

          ctx.font = `${fontSize * 0.85}px 'DM Mono', monospace`;
          ctx.fillStyle = node.color + '90';
          ctx.fillText(srcLabel, x, y0);

          ctx.font = `${fontSize}px 'DM Mono', monospace`;
          ctx.fillStyle = 'rgba(255,255,255,0.45)';
          let y = y0 + srcH;
          for (const ln of lines) {
            ctx.fillText(ln, x, y);
            y += lineH;
          }
        }
      }
    }
  })
  .nodePointerAreaPaint((node, color, ctx) => {
    ctx.fillStyle = color;
    ctx.beginPath();
    ctx.arc(node.x, node.y, 6, 0, 2 * Math.PI);
    ctx.fill();
  })
  .linkColor(l => {
    if (l.type === 'cross') return 'rgba(196,167,231,0.35)';
    const sn = typeof l.source === 'object' ? l.source : nodeMap[l.source];
    return sn ? sn.color + '18' : 'rgba(255,255,255,0.04)';
  })
  .linkWidth(l => {
    if (!activeNode()) return l.type === 'cross' ? 0.8 : 0.2;
    const sid = typeof l.source === 'object' ? l.source.id : l.source;
    const tid = typeof l.target === 'object' ? l.target.id : l.target;
    if (isConn(sid) && isConn(tid)) return l.type === 'cross' ? 2 : 0.5;
    return 0.05;
  })
  .linkDirectionalParticles(l => l.type === 'cross' ? 1 : 0)
  .linkDirectionalParticleWidth(2)
  .linkDirectionalParticleColor(() => '#c4a7e7')
  .linkDirectionalParticleSpeed(0.003)
  .linkLineDash(l => l.type === 'cross' ? [2, 2] : null)
  .linkCanvasObjectMode(l => {
    if (!activeNode()) return undefined;
    const sid = typeof l.source === 'object' ? l.source.id : l.source;
    const tid = typeof l.target === 'object' ? l.target.id : l.target;
    if (l.type !== 'cross') return undefined;
    if (isConn(sid) && isConn(tid)) return 'after';
    return undefined;
  })
  .linkCanvasObject((link, ctx) => {
    if (link.type !== 'cross' || !link.label) return;
    const s = typeof link.source === 'object' ? link.source : nodeMap[link.source];
    const t = typeof link.target === 'object' ? link.target : nodeMap[link.target];
    if (!s || !t) return;
    const mx = (s.x + t.x) / 2;
    const my = (s.y + t.y) / 2;
    const fontSize = 3;
    ctx.font = `${fontSize}px 'DM Mono', monospace`;
    ctx.fillStyle = 'rgba(196,167,231,0.7)';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(link.label, mx, my);
  })
  .onNodeHover(node => {
    document.body.style.cursor = node ? 'pointer' : 'default';
    hoverNode = node;
  })
  .onNodeClick(node => {
    selectedNode = node;
    showNode(node.id);
    Graph.centerAt(node.x, node.y, 800);
    Graph.zoom(4, 800);
  })
  .onLinkHover(link => {
    if (link && link.type === 'cross' && link.label) {
      edgeTooltip.textContent = link.label;
      edgeTooltip.style.display = 'block';
    } else {
      edgeTooltip.style.display = 'none';
    }
  })
  .onBackgroundClick(() => {
    selectedNode = null;
    closePanel();
    filterBookId = null;
    document.querySelectorAll('#legend .it').forEach(i => i.classList.remove('active'));
  })
  .cooldownTicks(200)
  .warmupTicks(100);

Graph.d3Force('charge').strength(-40);
Graph.d3Force('link').distance(l => l.type === 'cross' ? 100 : 25).strength(l => l.type === 'cross' ? 0.3 : 0.03);

document.addEventListener('mousemove', e => {
  edgeTooltip.style.left = (e.clientX + 12) + 'px';
  edgeTooltip.style.top = (e.clientY + 12) + 'px';
});

document.addEventListener('keydown', e => {
  if (e.key === 'Escape') {
    closePanel();
    hoverNode = null;
    filterBookId = null;
    document.querySelectorAll('#legend .it').forEach(i => i.classList.remove('active'));
  }
});
</script>
</body>
</html>'''


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Build highlight graph visualization')
    parser.add_argument('--highlights', required=True, help='Path to highlights JSON file')
    parser.add_argument('--connections', required=True, help='Path to connections JSON file')
    parser.add_argument('--output', default='highlight-graph.html', help='Output HTML file path')
    args = parser.parse_args()

    with open(args.highlights) as f:
        highlights = json.load(f)
    with open(args.connections) as f:
        connections = json.load(f)

    result = build_graph(highlights, connections, args.output)
    print(json.dumps(result))
